sudo: required
language: android
dist: precise
jdk:
  - oraclejdk8
env:
  global:
    DOCKER_TLS_VERIFY: 0
services:
  - docker
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew
  - echo "DOCKER_TLS_VERIFY = $DOCKER_TLS_VERIFY"

licenses:
  - android-sdk-license-.+

notifications:
  email: true

script: ./gradlew :library:clean :library:test