sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
env:
  global:
  - DOCKER_TLS_VERIFY: 0
  - DOCKER_HOST: http://localhost:2375

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - docker -v
  - chmod +x extra/install-android-sdk.sh
  - sudo ./extra/install-android-sdk.sh
  - ps aux | grep docker
  - chmod +x gradlew
  - echo "$ANDROID_HOME"
  - echo "PATH"
  - export ANDROID_HOME="/sdk"
  - export PATH="$PATH:${ANDROID_HOME}/tools"

notifications:
  email: true

script:
  - export ANDROID_HOME="/sdk"
  - export PATH="$PATH:${ANDROID_HOME}/tools"
  - ps aux | grep docker
  - ./gradlew :library:clean :library:test