sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
env:
  global:
  - DOCKER_TLS_VERIFY: 0
  - DOCKER_HOST: http://localhost:2376

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - docker -v
  - ./extra/install-android-sdk.sh
  - ps aux | grep docker
  - chmod +x gradlew

notifications:
  email: true

script:
  - ps aux | grep docker
  - ./gradlew :library:clean :library:test